default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "12345") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT", "tv_subscription_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "tv_subscription_test") %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DB_NAME_PRODUCTION", "tv_subscription_production") %>
    username: <%= ENV.fetch("DB_USERNAME_PRODUCTION", "tv_subscription") %>
    password: <%= ENV["TV_SUBSCRIPTION_DATABASE_PASSWORD"] %>

  cache:
    <<: *primary_production
    database: <%= ENV.fetch("DB_NAME_PRODUCTION_CACHE", "tv_subscription_production_cache") %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: <%= ENV.fetch("DB_NAME_PRODUCTION_QUEUE", "tv_subscription_production_queue") %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: <%= ENV.fetch("DB_NAME_PRODUCTION_CABLE", "tv_subscription_production_cable") %>
    migrations_paths: db/cable_migrate
